
deployment:
  name: promtail-gna
  label: promtail-gna
  replicas: 1
  image: gouthamrajanala/ec2-promtail:latest
  port: 3101

service:
  name: promtail-gna
  port: 3101
  type: LoadBalancer

config:
  lokiurl: http://internal-a3fafc6053c5f4cf09a3a65e16ab71c2-2015686658.us-east-1.elb.amazonaws.com:3100/loki/api/v1/push
  promtail:
    name: promtail-gna
    http_listen_port: 3101
    label: promtail-gna

